version: '3.8'

services:
  wg-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        WORKDIR_PATH: /workspaces/wg-gesucht-containerized
    ports:
      - "5000:5000" # Backend API
      - "3000:3000" # Frontend development server
    volumes:
      - .:/workspaces/wg-gesucht-containerized:cached
      - /workspaces/wg-gesucht-containerized/frontend/node_modules
      - ./app/data:/app/data
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    working_dir: /workspaces/wg-gesucht-containerized
    command: sleep infinity
    init: true
    user: root
